version: "3.8"

services:
  catalog.api:
    image: catalog-api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "5000:8080"  # Map API container port 8080 to localhost 5000
    environment:
      - MongoDB__ConnectionString=mongodb://admin:adminpassword@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
